import React, { useState } from 'react';
import { UserProfile } from '../lib/rag';

interface ResumeViewProps {
  profile: UserProfile | null;
}

export function ResumeView({ profile }: ResumeViewProps) {
  const [generating, setGenerating] = useState(false);

  const generatePDF = async () => {
    if (!profile) return;
    setGenerating(true);
    try {
      const { jsPDF } = await import('jspdf');
      const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });

      const pageW = 210;
      const margin = 18;
      const contentW = pageW - margin * 2;
      let y = 0;

      const addText = (text: string, options: { fontSize?: number; bold?: boolean; color?: [number, number, number]; align?: 'left' | 'center' | 'right'; marginTop?: number; maxWidth?: number } = {}) => {
        const { fontSize = 11, bold = false, color = [30, 30, 60], align = 'left', marginTop = 0, maxWidth = contentW } = options;
        y += marginTop;
        doc.setFontSize(fontSize);
        doc.setFont('helvetica', bold ? 'bold' : 'normal');
        doc.setTextColor(...color);
        const lines = doc.splitTextToSize(text, maxWidth);
        doc.text(lines, align === 'center' ? pageW / 2 : align === 'right' ? pageW - margin : margin, y, { align });
        y += (fontSize * 0.35 + 1) * lines.length;
        return y;
      };

      const addLine = (colorRgb: [number, number, number] = [0, 212, 212]) => {
        y += 2;
        doc.setDrawColor(...colorRgb);
        doc.setLineWidth(0.5);
        doc.line(margin, y, pageW - margin, y);
        y += 4;
      };

      const addSection = (title: string) => {
        addText(title.toUpperCase(), { fontSize: 10, bold: true, color: [0, 150, 180], marginTop: 6 });
        addLine([0, 180, 200]);
      };

      doc.setFillColor(15, 20, 50);
      doc.rect(0, 0, pageW, 42, 'F');

      y = 16;
      const name = `${profile.firstName} ${profile.lastName}`.trim() || 'Your Name';
      addText(name, { fontSize: 22, bold: true, color: [255, 255, 255], align: 'center' });

      y += 2;
      addText(profile.currentRole || 'Professional', { fontSize: 12, color: [0, 212, 212], align: 'center' });

      const contactParts = [profile.email, profile.location].filter(Boolean);
      if (contactParts.length) {
        y += 1;
        addText(contactParts.join(' · '), { fontSize: 9, color: [180, 200, 220], align: 'center' });
      }

      y = 52;

      if (profile.currentGoals) {
        addSection('Professional Summary');
        addText(profile.currentGoals, { fontSize: 10, color: [40, 40, 70], maxWidth: contentW });
      }

      if (profile.skills?.length) {
        addSection('Skills');
        const chunkSize = 5;
        for (let i = 0; i < profile.skills.length; i += chunkSize) {
          const row = profile.skills.slice(i, i + chunkSize).join('  ·  ');
          addText('• ' + row, { fontSize: 10, color: [40, 40, 70] });
          y += 1;
        }
      }

      if (profile.careerInterests?.length) {
        addSection('Career Interests');
        addText(profile.careerInterests.join(', '), { fontSize: 10, color: [40, 40, 70] });
      }

      if (profile.currentRole || profile.yearsOfExperience) {
        addSection('Experience');
        addText(profile.currentRole || 'Professional', { fontSize: 11, bold: true, color: [30, 30, 60] });
        if (profile.yearsOfExperience > 0) {
          addText(`${profile.yearsOfExperience} year${profile.yearsOfExperience !== 1 ? 's' : ''} of experience`, { fontSize: 10, color: [80, 80, 100] });
        }
        if (profile.challenges) {
          y += 1;
          addText(profile.challenges, { fontSize: 10, color: [60, 60, 90] });
        }
      }

      if (profile.educationLevel) {
        addSection('Education');
        addText(profile.educationLevel, { fontSize: 11, bold: true, color: [30, 30, 60] });
      }

      if (profile.availableHoursPerWeek || profile.preferredLearningStyle) {
        addSection('Learning & Availability');
        if (profile.availableHoursPerWeek) {
          addText(`Available: ${profile.availableHoursPerWeek} hours/week`, { fontSize: 10, color: [60, 60, 90] });
        }
        if (profile.preferredLearningStyle) {
          addText(`Learning Style: ${profile.preferredLearningStyle}`, { fontSize: 10, color: [60, 60, 90] });
        }
      }

      const totalPages = doc.getNumberOfPages();
      for (let i = 1; i <= totalPages; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(160, 160, 180);
        doc.text(`Generated by SahiPath · Page ${i} of ${totalPages}`, pageW / 2, 290, { align: 'center' });
      }

      doc.save(`${profile.firstName || 'Resume'}_${profile.lastName || ''}_Resume.pdf`.replace(/\s+/g, '_'));
    } catch (err) {
      console.error('PDF generation failed', err);
      alert('PDF generation failed. Please try again.');
    }
    setGenerating(false);
  };

  if (!profile?.firstName) {
    return (
      <div style={{ padding: '1.5rem', textAlign: 'center', color: 'var(--sp-text-secondary)' }}>
        Complete your profile first to generate a resume.
      </div>
    );
  }

  return (
    <div style={{ padding: '1.5rem' }}>
      <h3 style={{ marginTop: 0 }}>Resume Builder</h3>
      <p style={{ color: 'var(--sp-text-secondary)', fontSize: '0.9rem', marginBottom: '1.5rem' }}>
        Your resume is auto-filled from your profile data. Click below to download a professional PDF.
      </p>

      <div style={{ background: 'var(--sp-bg-tertiary)', borderRadius: 10, padding: '1.5rem', marginBottom: '1.5rem', borderLeft: '3px solid var(--sp-accent-teal)' }}>
        <div style={{ fontWeight: 700, fontSize: '1.1rem', marginBottom: '0.3rem' }}>{profile.firstName} {profile.lastName}</div>
        <div style={{ color: 'var(--sp-accent-teal)', marginBottom: '0.5rem', fontSize: '0.95rem' }}>{profile.currentRole}</div>
        <div style={{ fontSize: '0.85rem', color: 'var(--sp-text-secondary)', marginBottom: '0.3rem' }}>📧 {profile.email} {profile.location && `· 📍 ${profile.location}`}</div>
        {profile.yearsOfExperience > 0 && <div style={{ fontSize: '0.85rem', color: 'var(--sp-text-secondary)' }}>🏢 {profile.yearsOfExperience} years experience</div>}
        {profile.skills?.length > 0 && (
          <div style={{ marginTop: '0.8rem', display: 'flex', flexWrap: 'wrap', gap: '0.4rem' }}>
            {profile.skills.map(s => (
              <span key={s} style={{ background: 'rgba(0,212,212,0.1)', border: '1px solid var(--sp-accent-teal)', borderRadius: 12, padding: '0.2rem 0.6rem', fontSize: '0.75rem', color: 'var(--sp-accent-teal)' }}>{s}</span>
            ))}
          </div>
        )}
      </div>

      <div style={{ display: 'flex', gap: '0.8rem', flexWrap: 'wrap' }}>
        <button
          className="sp-btn-primary"
          onClick={generatePDF}
          disabled={generating}
          style={{ padding: '0.8rem 1.5rem', fontSize: '1rem' }}
        >
          {generating ? '⏳ Generating PDF...' : '📄 Download Resume (PDF)'}
        </button>
        <button
          className="sp-btn-secondary"
          onClick={() => {
            if (!profile) return;
            const txt = [
              `${profile.firstName} ${profile.lastName}`,
              profile.currentRole,
              profile.email,
              profile.location,
              '',
              'SKILLS',
              profile.skills?.join(', '),
              '',
              'CAREER INTERESTS',
              profile.careerInterests?.join(', '),
              '',
              'GOALS',
              profile.currentGoals,
            ].filter(l => l !== undefined).join('\n');
            const blob = new Blob([txt], { type: 'text/plain' });
            const a = document.createElement('a');
            a.href = URL.createObjectURL(blob);
            a.download = `${profile.firstName}_Resume.txt`;
            a.click();
          }}
          style={{ padding: '0.8rem 1.5rem' }}
        >
          📝 Download Resume (TXT)
        </button>
      </div>
    </div>
  );
}
