export const careerData = {
  frontend: {
    id: 'frontend',
    title: 'Frontend Engineer',
    stage: 'Best when you like building user interfaces and interactive products.',
    summary: 'Builds web interfaces, design systems, and accessible user experiences.',
    skills: ['HTML', 'CSS', 'JavaScript', 'React', 'Accessibility'],
    roadmap: ['Learn HTML/CSS', 'Master JavaScript', 'Learn React', 'Build 3 projects', 'Create portfolio'],
    freeResources: [
      { label: 'MDN Web Docs', url: 'https://developer.mozilla.org/', type: 'Documentation' },
      { label: 'freeCodeCamp', url: 'https://www.freecodecamp.org/', type: 'Course' }
    ],
    paidResources: [
      { label: 'Frontend Masters', url: 'https://frontendmasters.com/', type: 'Course' }
    ],
    testBank: ['Box model', 'React hooks', 'CSS Grid', 'State vs Props', 'Accessibility'],
    jobs: [
      { role: 'Frontend Intern', type: 'Internship' },
      { role: 'Junior React Dev', type: 'Full-time' }
    ]
  },
  data: {
    id: 'data',
    title: 'Data Analyst',
    stage: 'Best when you like patterns and business insights.',
    summary: 'Turns raw data into dashboards and decisions.',
    skills: ['Excel', 'SQL', 'Power BI', 'Statistics', 'Python'],
    roadmap: ['Learn Excel basics', 'Master SQL', 'Create dashboards', 'Analyze real data', 'Build portfolio'],
    freeResources: [
      { label: 'Kaggle Learn', url: 'https://www.kaggle.com/learn', type: 'Practice' },
      { label: 'Mode SQL Tutorial', url: 'https://mode.com/sql-tutorial/', type: 'SQL' }
    ],
    paidResources: [
      { label: 'DataCamp', url: 'https://www.datacamp.com/', type: 'Course' }
    ],
    testBank: ['SQL joins', 'Data cleaning', 'Statistics', 'Dashboard design', 'KPIs'],
    jobs: [
      { role: 'Data Analyst Intern', type: 'Internship' },
      { role: 'Business Analyst', type: 'Full-time' }
    ]
  },
  uiux: {
    id: 'uiux',
    title: 'UI/UX Designer',
    stage: 'Best when you love user behavior and design.',
    summary: 'Designs user journeys, wireframes, and prototypes.',
    skills: ['Figma', 'Design Systems', 'User Research', 'Prototyping', 'Accessibility'],
    roadmap: ['Learn design fundamentals', 'Create wireframes', 'Study Figma', 'User testing', 'Build case studies'],
    freeResources: [
      { label: 'Figma Design Resources', url: 'https://www.figma.com/', type: 'Tool' },
      { label: 'Nielsen Norman Group', url: 'https://www.nngroup.com/', type: 'Research' }
    ],
    paidResources: [
      { label: 'Interaction Design Foundation', url: 'https://www.interaction-design.org/', type: 'Course' }
    ],
    testBank: ['Usability', 'User interviews', 'Visual hierarchy', 'Personas', 'Prototyping'],
    jobs: [
      { role: 'UI/UX Intern', type: 'Internship' },
      { role: 'Product Designer', type: 'Full-time' }
    ]
  },
  cybersecurity: {
    id: 'cybersecurity',
    title: 'Cybersecurity Analyst',
    stage: 'Best when you like systems and protecting data.',
    summary: 'Protects systems with monitoring and incident response.',
    skills: ['Networking', 'Linux', 'Threat Modeling', 'SIEM', 'OWASP'],
    roadmap: ['Learn networking', 'Master Linux', 'Study OWASP Top 10', 'Home lab setup', 'Get certified'],
    freeResources: [
      { label: 'OWASP Top 10', url: 'https://owasp.org/', type: 'Security' },
      { label: 'PortSwigger Academy', url: 'https://portswigger.net/', type: 'Labs' }
    ],
    paidResources: [
      { label: 'TryHackMe', url: 'https://tryhackme.com/', type: 'Labs' }
    ],
    testBank: ['Phishing', 'Least privilege', 'Encryption', 'Vulnerabilities', 'Incident response'],
    jobs: [
      { role: 'SOC Analyst Intern', type: 'Internship' },
      { role: 'Security Analyst', type: 'Full-time' }
    ]
  },
  cloud: {
    id: 'cloud',
    title: 'Cloud/DevOps Engineer',
    stage: 'Best when you like infrastructure and automation.',
    summary: 'Builds deploy pipelines and production systems.',
    skills: ['Linux', 'Docker', 'Kubernetes', 'CI/CD', 'Cloud Platforms'],
    roadmap: ['Learn Linux', 'Master Docker', 'Study Kubernetes', 'Build CI/CD', 'Cloud certification'],
    freeResources: [
      { label: 'Docker Docs', url: 'https://docs.docker.com/', type: 'Documentation' },
      { label: 'AWS Skill Builder', url: 'https://skillbuilder.aws/', type: 'Course' }
    ],
    paidResources: [
      { label: 'KodeKloud', url: 'https://kodekloud.com/', type: 'Labs' }
    ],
    testBank: ['CI/CD', 'Docker', 'Infrastructure as Code', 'Monitoring', 'Scaling'],
    jobs: [
      { role: 'DevOps Intern', type: 'Internship' },
      { role: 'Cloud Engineer', type: 'Full-time' }
    ]
  },
  aiml: {
    id: 'aiml',
    title: 'AI/ML Engineer',
    stage: 'Best when you like math and intelligent systems.',
    summary: 'Builds models and intelligent products.',
    skills: ['Python', 'Statistics', 'TensorFlow', 'ML Algorithms', 'Data Processing'],
    roadmap: ['Learn Python', 'Study statistics', 'Master ML algorithms', 'Build projects', 'Deploy models'],
    freeResources: [
      { label: 'Google ML Crash Course', url: 'https://developers.google.com/machine-learning', type: 'Course' },
      { label: 'Kaggle', url: 'https://www.kaggle.com/', type: 'Competitions' }
    ],
    paidResources: [
      { label: 'DeepLearning.AI', url: 'https://www.deeplearning.ai/', type: 'Course' }
    ],
    testBank: ['Overfitting', 'Train-test split', 'Normalization', 'Precision/Recall', 'Model deployment'],
    jobs: [
      { role: 'ML Intern', type: 'Internship' },
      { role: 'ML Engineer', type: 'Full-time' }
    ]
  },
  product: {
    id: 'product',
    title: 'Product Manager',
    stage: 'Best when you like strategy and coordination.',
    summary: 'Shapes features and aligns teams.',
    skills: ['Roadmapping', 'Research', 'Metrics', 'Communication', 'Strategy'],
    roadmap: ['Learn PM basics', 'User interviews', 'Create roadmaps', 'Study metrics', 'Case studies'],
    freeResources: [
      { label: 'Mind the Product', url: 'https://www.mindtheproduct.com/', type: 'Articles' },
      { label: 'Lenny Rachitsky', url: 'https://www.lennysnewsletter.com/', type: 'Newsletter' }
    ],
    paidResources: [
      { label: 'Reforge', url: 'https://www.reforge.com/', type: 'Course' }
    ],
    testBank: ['Product-market fit', 'Prioritization', 'KPIs', 'PRD writing', 'User retention'],
    jobs: [
      { role: 'Product Manager Intern', type: 'Internship' },
      { role: 'APM (Associate PM)', type: 'Full-time' }
    ]
  }
};

export const translations: any = {
  English: {
    personal_details: 'Personal Details',
    professional_details: 'Professional Details',
    tell_us_about: 'Tell us about yourself so we can personalize your experience',
    career_info: 'Help us understand your career goals and learning preferences',
    firstName: 'First Name *',
    lastName: 'Last Name',
    age: 'Age',
    email: 'Email *',
    location: 'Location (City/Country)',
    currentRole: 'Current Role/Job Title *',
    yearsExp: 'Years of Experience',
    skills: 'Skills',
    interests: 'Career Interests',
    goals: 'Current Goals',
    challenges: 'Challenges',
    hoursPerWeek: 'Hours available per week',
    learningStyle: 'Learning Style',
    alert_fillRequired: 'Please fill all required fields',
    next: 'Next',
    back: 'Back',
    startMentoring: 'Start Mentoring',
    mentorChat: 'AI Career Mentor',
    rag_intro: '24/7 AI Assistant powered by your personal career context',
    profile_summary: 'Your Profile',
    role: 'Role',
    years: 'years',
    hours: 'hours',
    restart: 'Restart',
    askAnything: 'Ask me anything...',
    send: 'Send',
    edu_highschool: 'High School',
    edu_bachelor: 'Bachelor\'s',
    edu_master: 'Master\'s',
    edu_phd: 'PhD',
  },
  Hindi: {
    personal_details: 'व्यक्तिगत विवरण',
    professional_details: 'व्यावसायिक विवरण',
    tell_us_about: 'अपने बारे में बताएं ताकि हम आपके अनुभव को व्यक्तिगत बना सकें',
    career_info: 'हमें अपने करियर लक्ष्यों और सीखने की प्राथमिकताओं को समझने में मदद करें',
    firstName: 'पहला नाम *',
    lastName: 'अंतिम नाम',
    age: 'आयु',
    email: 'ईमेल *',
    location: 'स्थान (शहर/देश)',
    currentRole: 'वर्तमान भूमिका/नौकरी का शीर्षक *',
    yearsExp: 'वर्षों का अनुभव',
    skills: 'कौशल',
    interests: 'करियर रुचियां',
    goals: 'वर्तमान लक्ष्य',
    challenges: 'चुनौतियां',
    hoursPerWeek: 'प्रति सप्ताह उपलब्ध घंटे',
    learningStyle: 'सीखने की शैली',
    alert_fillRequired: 'कृपया सभी आवश्यक क्षेत्र भरें',
    next: 'अगला',
    back: 'वापस',
    startMentoring: 'मेंटरिंग शुरू करें',
    mentorChat: 'एआई करियर मेंटर',
    rag_intro: '24/7 एआई सहायक जो आपके व्यक्तिगत करियर संदर्भ द्वारा संचालित है',
    profile_summary: 'आपका प्रोफ़ाइल',
    role: 'भूमिका',
    years: 'साल',
    hours: 'घंटे',
    restart: 'फिर से शुरू करें',
    askAnything: 'कुछ भी पूछें...',
    send: 'भेजें',
    edu_highschool: 'हाई स्कूल',
    edu_bachelor: 'स्नातक',
    edu_master: 'स्नातकोत्तर',
    edu_phd: 'पीएचडी',
  },
  Tamil: {
    personal_details: 'தனிப்பட்ட விவரங்கள்',
    professional_details: 'தொழிலாளர் விவரங்கள்',
    tell_us_about: 'உங்களைப் பற்றி சொல்லுங்கள் - உங்கள் அனுபவத்தை நாம் தனிப்பயனாக்க முடியும்',
    career_info: 'உங்கள் வேலை இலக்குகள் மற்றும் கற்றல் விருப்பங்களைப் புரிந்துகொள்ள எங்களுக்கு உதவுங்கள்',
    firstName: 'முதல் பெயர் *',
    lastName: 'கடைசி பெயர்',
    age: 'வயது',
    email: 'மின்னஞ்சல் *',
    location: 'இடம் (நகரம்/நாடு)',
    currentRole: 'தற்போதைய பாத்திரம்/பணியின் தலைப்பு *',
    yearsExp: 'அனுபவ வருடங்கள்',
    skills: 'திறன்கள்',
    interests: 'வேலை ஆர்வம்',
    goals: 'தற்போதைய இலக்குகள்',
    challenges: 'சவால்கள்',
    hoursPerWeek: 'வாரத்திற்கு கிடைக்கும் மணிநேரம்',
    learningStyle: 'கற்றல் பாணி',
    alert_fillRequired: 'பயனுள்ள அனைத்து புலங்களை நிரப்பவும்',
    next: 'அடுத்த',
    back: 'மீண்டும்',
    startMentoring: 'வழிகாட்டுதல் தொடங்கவும்',
    mentorChat: 'AI வேலை ஆலோசகர்',
    rag_intro: '24/7 AI உதவியாளர் - உங்கள் தனிப்பட்ட வேலை சூழல்களால் செயல்படுத்தப்படுகிறது',
    profile_summary: 'உங்கள் சுயவிவரம்',
    role: 'பாத்திரம்',
    years: 'ஆண்டுகள்',
    hours: 'மணிநேரம்',
    restart: 'மீண்டும் தொடங்கவும்',
    askAnything: 'எதையும் கேளுங்கள்...',
    send: 'அனுப்பவும்',
    edu_highschool: 'பள்ளி',
    edu_bachelor: 'இளங்கலை',
    edu_master: 'முதுநிலை',
    edu_phd: 'பிஎச்டி',
  },
  Telugu: {
    personal_details: 'వ్యక్తిగత వివరాలు',
    professional_details: 'వృత్తిపరమైన వివరాలు',
    tell_us_about: 'మీ గురించి చెప్పండి - మేము మీ అనుభవాన్ని ব్యక్తిగతం చేయవచ్చు',
    career_info: 'మీ కెరీర్ లక్ష్యాలు మరియు నేర్పు ప్రాధాన్యతలను అర్థం చేసుకోవడానికి సహాయం చేయండి',
    firstName: 'మొదటి పేరు *',
    lastName: 'చివరి పేరు',
    age: 'వయస్సు',
    email: 'ఈమెయిల్ *',
    location: 'ప్రదేశం (నగరం/దేశం)',
    currentRole: 'ప్రస్తుత పాత్ర/ఉద్యోగ శీర్షిక *',
    yearsExp: 'అనుభవ సంవత్సరాలు',
    skills: 'నైపుణ్యాలు',
    interests: 'కెరీర్ ఆసక్తులు',
    goals: 'ప్రస్తుత లక్ష్యాలు',
    challenges: 'సవాళ్లు',
    hoursPerWeek: 'వారానికి లభ్యమైన గంటలు',
    learningStyle: 'నేర్పు శైలి',
    alert_fillRequired: 'దయచేసి అన్ని అవసరమైన ఖాళీలను పూరించండి',
    next: 'తరువాత',
    back: 'వెనక్కి',
    startMentoring: 'మెంటోరింగ్ ప్రారంభించండి',
    mentorChat: 'AI కెరీర్ మెంటర్',
    rag_intro: '24/7 AI సహాయक - మీ వ్యక్తిగత కెరీర్ సందర్భం ద్వారా ప్రపంచిత',
    profile_summary: 'మీ ప్రొఫైల్',
    role: 'పాత్ర',
    years: 'సంవత్సరాలు',
    hours: 'గంటలు',
    restart: 'పునः ప్రారంభించండి',
    askAnything: 'ఏదైనా అడగండి...',
    send: 'పంపండి',
    edu_highschool: 'హై స్కూల్',
    edu_bachelor: 'బాచిలర్',
    edu_master: 'మాస్టర్స్',
    edu_phd: 'పిహెచ్డి',
  },
  Kannada: {
    personal_details: 'ವ್ಯಕ್ತಿಗತ ವಿವರಗಳು',
    professional_details: 'ವೃತ್ತಿಪರ ವಿವರಗಳು',
    tell_us_about: 'ನಿಮ್ಮ ಬಗ್ಗೆ ಹೇಳಿ - ನಾವು ನಿಮ್ಮ ಅನುಭವವನ್ನು ವ್ಯಕ್ತಿಗತಗೊಳಿಸಬಹುದು',
    career_info: 'ನಿಮ್ಮ ವೃತ್ತಿ ಗುರಿಗಳು ಮತ್ತು ಕಲಿಕೆಯ ಆದ್ಯತೆಗಳನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಲು ಸಹಾಯ ಮಾಡಿ',
    firstName: 'ಮೊದಲ ಹೆಸರು *',
    lastName: 'ಕೊನೆಯ ಹೆಸರು',
    age: 'ವಯಸ್ಸು',
    email: 'ಇಮೇಲ್ *',
    location: 'ಸ್ಥಳ (ನಗರ/ದೇಶ)',
    currentRole: 'ಪ್ರಸ್ತುತ ಭೂಮಿಕೆ/ಉದ್ಯೋಗ ಶೀರ್ಷಿಕೆ *',
    yearsExp: 'ಅನುಭವದ ವರ್ಷಗಳು',
    skills: 'ಕೌಶಲ್ಯಗಳು',
    interests: 'ವೃತ್ತಿ ಆಸಕ್ತಿಗಳು',
    goals: 'ಪ್ರಸ್ತುತ ಗುರಿಗಳು',
    challenges: 'ಸವಾಲುಗಳು',
    hoursPerWeek: 'ಪ್ರತಿ ವಾರ ಲಭ್ಯವಿರುವ ಘಂಟೆಗಳು',
    learningStyle: 'ಕಲಿಕೆ ಪದ್ಧತಿ',
    alert_fillRequired: 'ದಯವಿಟ್ಟು ಎಲ್ಲಾ ಅಗತ್ಯವಿರುವ ಕ್ಷೇತ್ರಗಳನ್ನು ಭರ್ತಿ ಮಾಡಿ',
    next: 'ಮುಂದೆ',
    back: 'ಹಿಂದೆ',
    startMentoring: 'ಮೆಂಟರಿಂಗ್ ಪ್ರಾರಂಭಿಸಿ',
    mentorChat: 'AI ವೃತ್ತಿ ಸಲಹೆಗಾರ',
    rag_intro: '24/7 AI ಸಹಾಯಕ - ನಿಮ್ಮ ವ್ಯಕ್ತಿಗತ ವೃತ್ತಿ ಸನ್ನಿವೇಶದ ಮೂಲಕ ಚಾಲಿತ',
    profile_summary: 'ನಿಮ್ಮ ಪ್ರೊಫೈಲ್',
    role: 'ಭೂಮಿಕೆ',
    years: 'ವರ್ಷಗಳು',
    hours: 'ಘಂಟೆ',
    restart: 'ಮರುಪ್ರಾರಂಭಿಸಿ',
    askAnything: 'ಯಾವುದೇ ವಿಷಯ ಕೇಳಿ...',
    send: 'ಕಳುಹಿಸಿ',
    edu_highschool: 'ಹೈ ಸ್ಕೂಲ್',
    edu_bachelor: 'ಬ್ಯಾಚಲರ್',
    edu_master: 'ಮಾಸ್ಟರ್',
    edu_phd: 'ಪಿಎಚ್.ಡಿ',
  },
  Malayalam: {
    personal_details: 'വ്യക്തിഗത വിവരങ്ങൾ',
    professional_details: 'പ്രൊഫഷണൽ വിവരങ്ങൾ',
    tell_us_about: 'നിങ്ങളെക്കുറിച്ച് പറയുക - നിങ്ങളുടെ അനുഭവം ഞാൻ വ്യക്തിഗതമാക്കുന്നു',
    career_info: 'നിങ്ങളുടെ കരിയർ ലക്ഷ്യങ്ങളും പഠന മുൻഗണനകളും മനസ്സിലാക്കാൻ സഹായിക്കുക',
    firstName: 'ആദ്യ നാമം *',
    lastName: 'അവസാന നാമം',
    age: 'പ്രായം',
    email: 'ഇമെയിൽ *',
    location: 'സ്ഥലം (നഗരം/രാജ്യം)',
    currentRole: 'നിലവിലെ പങ്ക് / ജോലി ശീർഷകം *',
    yearsExp: 'അനുഭവത്തിന്റെ വർഷങ്ങൾ',
    skills: 'കഴിവുകൾ',
    interests: 'കരിയർ താൽപ്പര്യങ്ങൾ',
    goals: 'നിലവിലെ ലക്ഷ്യങ്ങൾ',
    challenges: 'വെല്ലുവിളികൾ',
    hoursPerWeek: 'വാരത്തിൽ ലഭ്യമായ മണിക്കൂറുകൾ',
    learningStyle: 'പഠന ശൈലി',
    alert_fillRequired: 'ദയവായി എല്ലാ ആവശ്യമായ ഫീൽഡുകൾ പൂരിപ്പിക്കുക',
    next: 'അടുത്തത്',
    back: 'പിന്നിലേക്ക്',
    startMentoring: 'മെന്റോറിംഗ് ആരംഭിക്കുക',
    mentorChat: 'AI കരിയർ മെന്റർ',
    rag_intro: '24/7 AI സഹായി - നിങ്ങളുടെ ব്യക്തിഗത കരിയർ സന്ദർഭം ഉപയോഗിച്ച് പ്രേരിത',
    profile_summary: 'നിങ്ങളുടെ പ്രൊഫൈൽ',
    role: 'പങ്ക്',
    years: 'വർഷങ്ങൾ',
    hours: 'മണിക്കൂറുകൾ',
    restart: 'വീണ്ടും ആരംഭിക്കുക',
    askAnything: 'എന്തെങ്കിലും ചോദിക്കുക...',
    send: 'അയയ്ക്കുക',
    edu_highschool: 'ഹൈ സ്കൂൾ',
    edu_bachelor: 'ബാച്ചിലർ',
    edu_master: 'മാസ്റ്റർ',
    edu_phd: 'പി.എച്ച്.ഡി',
  },
  Spanish: {
    personal_details: 'Detalles Personales',
    professional_details: 'Detalles Profesionales',
    tell_us_about: 'Cuéntanos sobre ti para que podamos personalizar tu experiencia',
    career_info: 'Ayúdanos a entender tus objetivos de carrera y preferencias de aprendizaje',
    firstName: 'Nombre *',
    lastName: 'Apellido',
    age: 'Edad',
    email: 'Correo Electrónico *',
    location: 'Ubicación (Ciudad/País)',
    currentRole: 'Función/Puesto Actual *',
    yearsExp: 'Años de Experiencia',
    skills: 'Habilidades',
    interests: 'Intereses de Carrera',
    goals: 'Objetivos Actuales',
    challenges: 'Desafíos',
    hoursPerWeek: 'Horas disponibles por semana',
    learningStyle: 'Estilo de Aprendizaje',
    alert_fillRequired: 'Por favor completa todos los campos requeridos',
    next: 'Siguiente',
    back: 'Atrás',
    startMentoring: 'Iniciar Mentoría',
    mentorChat: 'Mentor de Carrera IA',
    rag_intro: 'Asistente IA 24/7 impulsado por tu contexto de carrera personal',
    profile_summary: 'Tu Perfil',
    role: 'Función',
    years: 'años',
    hours: 'horas',
    restart: 'Reiniciar',
    askAnything: 'Pregunta cualquier cosa...',
    send: 'Enviar',
    edu_highschool: 'High School',
    edu_bachelor: 'Licenciatura',
    edu_master: 'Máster',
    edu_phd: 'Doctorado',
  },
  French: {
    personal_details: 'Détails Personnels',
    professional_details: 'Détails Professionnels',
    tell_us_about: 'Parlez-nous de vous pour que nous puissions personnaliser votre expérience',
    career_info: 'Aidez-nous à comprendre vos objectifs de carrière et vos préférences d\'apprentissage',
    firstName: 'Prénom *',
    lastName: 'Nom',
    age: 'Âge',
    email: 'Email *',
    location: 'Localisation (Ville/Pays)',
    currentRole: 'Fonction/Titre Actuel *',
    yearsExp: 'Années d\'Expérience',
    skills: 'Compétences',
    interests: 'Intérêts de Carrière',
    goals: 'Objectifs Actuels',
    challenges: 'Défis',
    hoursPerWeek: 'Heures disponibles par semaine',
    learningStyle: 'Style d\'Apprentissage',
    alert_fillRequired: 'Veuillez remplir tous les champs obligatoires',
    next: 'Suivant',
    back: 'Retour',
    startMentoring: 'Commencer le Mentorat',
    mentorChat: 'Mentor de Carrière IA',
    rag_intro: 'Assistant IA 24/7 alimenté par votre contexte de carrière personnel',
    profile_summary: 'Votre Profil',
    role: 'Fonction',
    years: 'ans',
    hours: 'heures',
    restart: 'Redémarrer',
    askAnything: 'Posez n\'importe quelle question...',
    send: 'Envoyer',
    edu_highschool: 'Lycée',
    edu_bachelor: 'Licence',
    edu_master: 'Master',
    edu_phd: 'Doctorat',
  },
  German: {
    personal_details: 'Persönliche Daten',
    professional_details: 'Berufliche Details',
    tell_us_about: 'Erzählen Sie uns von sich, um Ihr Erlebnis zu personalisieren',
    career_info: 'Helfen Sie uns, Ihre Karriereziele und Lernvorlieben zu verstehen',
    firstName: 'Vorname *',
    lastName: 'Nachname',
    age: 'Alter',
    email: 'E-Mail *',
    location: 'Standort (Stadt/Land)',
    currentRole: 'Aktuelle Rolle/Jobtitel *',
    yearsExp: 'Jahre Erfahrung',
    skills: 'Fähigkeiten',
    interests: 'Karriereinteressen',
    goals: 'Aktuelle Ziele',
    challenges: 'Herausforderungen',
    hoursPerWeek: 'Verfügbare Stunden pro Woche',
    learningStyle: 'Lernstil',
    alert_fillRequired: 'Bitte füllen Sie alle erforderlichen Felder aus',
    next: 'Weiter',
    back: 'Zurück',
    startMentoring: 'Mentoring starten',
    mentorChat: 'KI-Karrierementor',
    rag_intro: '24/7 KI-Assistent angetrieben durch Ihren persönlichen Karrierekontext',
    profile_summary: 'Ihr Profil',
    role: 'Rolle',
    years: 'Jahre',
    hours: 'Stunden',
    restart: 'Neustart',
    askAnything: 'Fragen Sie alles...',
    send: 'Senden',
    edu_highschool: 'High School',
    edu_bachelor: 'Bachelor',
    edu_master: 'Master',
    edu_phd: 'Promotion',
  },
  Chinese: {
    personal_details: '个人详情',
    professional_details: '专业详情',
    tell_us_about: '告诉我们关于您的信息，以便我们可以个性化您的体验',
    career_info: '帮助我们了解您的职业目标和学习偏好',
    firstName: '名字 *',
    lastName: '姓氏',
    age: '年龄',
    email: '电子邮件 *',
    location: '位置（城市/国家）',
    currentRole: '当前职位 *',
    yearsExp: '工作经验年数',
    skills: '技能',
    interests: '职业兴趣',
    goals: '当前目标',
    challenges: '挑战',
    hoursPerWeek: '每周可用小时数',
    learningStyle: '学习风格',
    alert_fillRequired: '请填写所有必填字段',
    next: '下一步',
    back: '返回',
    startMentoring: '开始指导',
    mentorChat: 'AI 职业导师',
    rag_intro: '24/7 AI 助手由您的个人职业背景驱动',
    profile_summary: '您的个人资料',
    role: '角色',
    years: '年',
    hours: '小时',
    restart: '重新开始',
    askAnything: '问我任何事...',
    send: '发送',
    edu_highschool: '中学',
    edu_bachelor: '学士',
    edu_master: '硕士',
    edu_phd: '博士',
  },
  Japanese: {
    personal_details: '個人情報',
    professional_details: '専門情報',
    tell_us_about: 'あなたについて教えてください - 経験をパーソナライズします',
    career_info: 'キャリア目標と学習嗜好を理解するのをお手伝いください',
    firstName: '名前 *',
    lastName: '苗字',
    age: '年齢',
    email: 'メール *',
    location: '場所（都市/国）',
    currentRole: '現在の役職/職種 *',
    yearsExp: '経験年数',
    skills: 'スキル',
    interests: 'キャリアの興味',
    goals: '現在の目標',
    challenges: 'チャレンジ',
    hoursPerWeek: '週間利用可能時間',
    learningStyle: '学習スタイル',
    alert_fillRequired: 'すべての必須フィールドを入力してください',
    next: '次へ',
    back: '戻る',
    startMentoring: 'メンタリングを開始',
    mentorChat: 'AI キャリアメンター',
    rag_intro: '24/7 AI アシスタント - あなたの個人的なキャリアコンテキストを搭載',
    profile_summary: 'あなたのプロフィール',
    role: '役割',
    years: '年',
    hours: '時間',
    restart: '再起動',
    askAnything: '何でも質問してください...',
    send: '送信',
    edu_highschool: '高校',
    edu_bachelor: '学士',
    edu_master: '修士',
    edu_phd: '博士号',
  },
  Portuguese: {
    personal_details: 'Detalhes Pessoais',
    professional_details: 'Detalhes Profissionais',
    tell_us_about: 'Conte-nos sobre você para personalizarmos sua experiência',
    career_info: 'Ajude-nos a entender seus objetivos de carreira e preferências de aprendizado',
    firstName: 'Primeiro Nome *',
    lastName: 'Sobrenome',
    age: 'Idade',
    email: 'Email *',
    location: 'Localização (Cidade/País)',
    currentRole: 'Função/Cargo Atual *',
    yearsExp: 'Anos de Experiência',
    skills: 'Habilidades',
    interests: 'Interesses de Carreira',
    goals: 'Objetivos Atuais',
    challenges: 'Desafios',
    hoursPerWeek: 'Horas disponíveis por semana',
    learningStyle: 'Estilo de Aprendizado',
    alert_fillRequired: 'Por favor, preencha todos os campos obrigatórios',
    next: 'Próximo',
    back: 'Voltar',
    startMentoring: 'Iniciar Mentoria',
    mentorChat: 'Mentor de Carreira IA',
    rag_intro: 'Assistente IA 24/7 alimentado pelo seu contexto de carreira pessoal',
    profile_summary: 'Seu Perfil',
    role: 'Função',
    years: 'anos',
    hours: 'horas',
    restart: 'Reiniciar',
    askAnything: 'Pergunte qualquer coisa...',
    send: 'Enviar',
    edu_highschool: 'Ensino Médio',
    edu_bachelor: 'Bacharel',
    edu_master: 'Mestrado',
    edu_phd: 'Doutorado',
  },
  Arabic: {
    personal_details: 'التفاصيل الشخصية',
    professional_details: 'التفاصيل المهنية',
    tell_us_about: 'أخبرنا عن نفسك حتى نتمكن من تخصيص تجربتك',
    career_info: 'ساعدنا في فهم أهداف حياتك المهنية وتفضيلات التعلم',
    firstName: 'الاسم الأول *',
    lastName: 'الكنية',
    age: 'العمر',
    email: 'البريد الإلكتروني *',
    location: 'الموقع (المدينة / الدولة)',
    currentRole: 'الدور الحالي / سمة الوظيفة *',
    yearsExp: 'سنوات الخبرة',
    skills: 'المهارات',
    interests: 'اهتمامات الحياة المهنية',
    goals: 'الأهداف الحالية',
    challenges: 'التحديات',
    hoursPerWeek: 'الساعات المتاحة في الأسبوع',
    learningStyle: 'أسلوب التعلم',
    alert_fillRequired: 'يرجى ملء جميع الحقول المطلوبة',
    next: 'التالي',
    back: 'خلف',
    startMentoring: 'ابدأ الإرشاد',
    mentorChat: 'مرشد الذكاء الاصطناعي الوظيفي',
    rag_intro: 'مساعد ذكاء اصطناعي 24/7 مدعوم بسياقك الوظيفي الشخصي',
    profile_summary: 'ملفك الشخصي',
    role: 'دور',
    years: 'سنوات',
    hours: 'ساعات',
    restart: 'إعادة تشغيل',
    askAnything: 'اسأل أي شيء...',
    send: 'إرسال',
    edu_highschool: 'المدرسة الثانوية',
    edu_bachelor: 'بكالوريوس',
    edu_master: 'ماجستير',
    edu_phd: 'دكتوراه',
  },
  Korean: {
    personal_details: '개인 정보',
    professional_details: '직업 정보',
    tell_us_about: '자신에 대해 알려주세요 - 경험을 개인화하겠습니다',
    career_info: '경력 목표 및 학습 선호도를 이해하도록 도와주세요',
    firstName: '이름 *',
    lastName: '성 *',
    age: '나이',
    email: '이메일 *',
    location: '위치 (도시/국가)',
    currentRole: '현재 직급/직책 *',
    yearsExp: '경력년수',
    skills: '기술',
    interests: '경력 관심사',
    goals: '현재 목표',
    challenges: '과제',
    hoursPerWeek: '주당 사용 가능 시간',
    learningStyle: '학습 스타일',
    alert_fillRequired: '필수 필드를 모두 입력하세요',
    next: '다음',
    back: '뒤로',
    startMentoring: '멘토링 시작',
    mentorChat: 'AI 커리어 멘토',
    rag_intro: '24/7 AI 어시스턴트 - 개인 경력 맥락으로 제공',
    profile_summary: '프로필',
    role: '직책',
    years: '년',
    hours: '시간',
    restart: '재시작',
    askAnything: '뭔가 물어보세요...',
    send: '전송',
    edu_highschool: '고등학교',
    edu_bachelor: '학사',
    edu_master: '석사',
    edu_phd: '박사',
  },
};

export const languageInfo: Record<string, { emoji: string; nativeName: string; englishName: string; region: string }> = {
  English: { emoji: '🇬🇧', nativeName: 'English', englishName: 'English', region: 'Global' },
  Hindi: { emoji: '🇮🇳', nativeName: 'हिंदी', englishName: 'Hindi', region: 'India' },
  Tamil: { emoji: '🇮🇳', nativeName: 'தமிழ்', englishName: 'Tamil', region: 'India' },
  Telugu: { emoji: '🇮🇳', nativeName: 'తెలుగు', englishName: 'Telugu', region: 'India' },
  Kannada: { emoji: '🇮🇳', nativeName: 'ಕನ್ನಡ', englishName: 'Kannada', region: 'India' },
  Malayalam: { emoji: '🇮🇳', nativeName: 'മലയാളം', englishName: 'Malayalam', region: 'India' },
  Spanish: { emoji: '🇪🇸', nativeName: 'Español', englishName: 'Spanish', region: 'Global' },
  French: { emoji: '🇫🇷', nativeName: 'Français', englishName: 'French', region: 'Global' },
  German: { emoji: '🇩🇪', nativeName: 'Deutsch', englishName: 'German', region: 'Global' },
  Chinese: { emoji: '🇨🇳', nativeName: '中文', englishName: 'Chinese', region: 'Global' },
  Japanese: { emoji: '🇯🇵', nativeName: '日本語', englishName: 'Japanese', region: 'Global' },
  Portuguese: { emoji: '🇵🇹', nativeName: 'Português', englishName: 'Portuguese', region: 'Global' },
  Arabic: { emoji: '🇸🇦', nativeName: 'العربية', englishName: 'Arabic', region: 'Global' },
  Korean: { emoji: '🇰🇷', nativeName: '한국어', englishName: 'Korean', region: 'Global' },
};
